### ISSUE TITLE
Record Text Input with Special characters issues

### ISSUE THREAD

**Issue by aqiftekhar** [Blazemeter/CitrixPlugin#30]
Hi,

I am trying to record a text input i.e. Password string. and password is "P@&&w0rd" in this case, i have noticed that it do not treat as as text but as a sequence. suppose i have to login using multiple accounts, then in this case the sequence will be hard-coded. Can you suggest me how to deal with this?

**Comment by aqiftekhar** [comment]
another example is of "SHIFT + 4" so how to handle such cases? Thanks in advance

**Comment by 3dgiordano** [comment]
Hi @aqiftekhar sorry for the delay in answering. We were in a plugin owner transition process.
Now I will be in charge of it helping you with everything related to the plugin.

It is true that when it starts, a password is requested to start recording.
Then for the execution mode that pre-parameterized variable is also used.
To be able to run multiple users in the Thread-Group, it is necessary to make an adaptation so that in each Thread in Thread-Group set that variable and the user variable with a different user for each thread.

For this it is possible to use CSV Data Set Config in Sharing Mode, in "All threads" mode
https://www.blazemeter.com/blog/csv-data-set-config-in-sharing-mode-made-easy

In this way, each thread will be assigned a csv user and it will not be repeated, not causing conflicts if you don't have configured in Citrix that no more than one session is allowed per user.

A new version of the plugin was released.
Make sure to test with the new version, it has multiple fixes related to the support of runs with multiple users.

On the recording of texts, it records sequences of keystrokes, the down of the key shift, the pressure of the text 4 and the up of the key shift.
Internally, the Citrix protocol is handled that way, it is true that an improvement could be made and try to handle these states automatically. We will take it as a suggestion for improvement.
However it is not an issue, currently it is possible to write any ascii character.

If you have any problems with the recording of the key sequences with the new version, let us know.

**Comment by 3dgiordano** [comment]
Hi @aqiftekhar
The next version will have improvements in InputText that will allow better interaction with the Citrix keyboard simulation.
Key sequences will be captured and extended characters will be supported.
You can also use parameters for writing, so you can not only capture more, you can send text from different sources.
