### ISSUE TITLE
Issue downloading ICA file, please share sample template data entries

### ISSUE THREAD

**Issue by AnuragChourasia** [Blazemeter/CitrixPlugin#44]
Hi, 
 I am first time trying BlazeMeter CitrixPlugin to performance test  my Desktop based application published through Citrix. I am having trouble downloading ICA file. Please find attached doc with detailed information.

Thanks in advance for your help.

[CitrixPlugIn Issue in ICA download.docx](https://github.com/Blazemeter/CitrixPlugin/files/6035911/CitrixPlugIn.Issue.in.ICA.download.docx)

**Comment by 3dgiordano** [comment]
Hi @AnuragChourasia 

Reviewing the attached, I notice that in citrix_portal_context_path you have a complete URL.
Only the path must be indicated, without protocol or host.

It should be in your case the following value
```
/Citrix/ExternalWeb
```
If you look at the http request, in the view result tree, selecting HP-2, you will see the http request and the url used. 
Surely the malformed URL and the http error should be evidenced there.

Try the new value and tell me if this fixes the problem.

**Comment by ANURAG-CHOURASIA-BY** [comment]
Hi,
Sorry for replying late because I was awaiting a new Citrix setup for my testing. I tried Context path as per you suggestion but it still errors out please advice. Thanks

Thanks
[CitrixPlugIn.docx](https://github.com/Blazemeter/CitrixPlugin/files/6105627/CitrixPlugIn.docx)

**Comment by AnuragChourasia** [comment]
Hi,
I removed the "https://" part and tried but it still gives me error. I attached all screens with error in case that helps to pin point the main issue.

Thanks again for your help.

[CitrixPlugIn_screens.docx](https://github.com/Blazemeter/CitrixPlugin/files/6108533/CitrixPlugIn_screens.docx)

**Comment by AnuragChourasia** [comment]
@3dgiordano, would really appreciate your help in resolving my issue here..
Or could you please advice some other consultant who can help me resolving this issue and answer any other queries on Citrix Plug-in with JMeter in going forward.

Thanks

**Comment by gooflee** [comment]
I had the same issue as you had in the screenshot.  It seems that our Citrix configuration doesn't exactly match what the Test Fragment is expecting., so I ended up modifying the Test Fragment so that it better matches our environment.  I used this as a template and create new scripts based off of it.  It works for our environment, so it may work for yours.  Rename the file to .jmx.
[Citrix2_empty.txt](https://github.com/Blazemeter/CitrixPlugin/files/6541298/Citrix2_empty.txt)

**Comment by AnuragChourasia** [comment]
@gooflee  Thanks for sharing these details.. Sorry for responding late since I left my Citrix testing due to this issue.
I have got time now to work on this again. I copied the file you had shared and renamed file name with extension .jmx and loaded to JMeter. made the changes to my environment specific but issue still exists in downloading ICA file.

Thanks

**Comment by 3dgiordano** [comment]
Hi @AnuragChourasia 

We are needing you to capture the traffic from the beginning of the login to the StoreFront portal, including the download of the ICA File, in order to recognize which version of the portal is currently in use and what is the difference in the expected http and your portal.

You can use several different methods to record the traffic.

- JMeter Proxy to record the traffic and send us the jmx, using the manual of JMeter Proxy https://jmeter.apache.org/usermanual/jmeter_proxy_step_by_step.html

- HAR file, using a browser,
https://knowledge.broadcom.com/external/article/170836/obtain-a-har-file.html

It is necessary to open these files with a text editor and remove sensible information such as domain names, users and passwords (har file is a zip file, rename first to zip, extract and modify the content and share that files)

To maintain security on the shared,, you can share it via Google Drive or Box and send me the link to david.giordano@broadcom.com

When I have the file to analyze, you can unpublish the link for better security.

**Comment by AnuragChourasia** [comment]
Hi David, as requested I shared HAR file with you through Gdrive.

Thank for your support.

**Comment by AnuragChourasia** [comment]
@3dgiordano 3dgiordano please let me know if you need further details.
Thanks.

**Comment by AnuragChourasia** [comment]
@3dgiordano @gooflee  Can you please help here?
Thanks

**Comment by 3dgiordano** [comment]
Hi @AnuragChourasia 
Sorry for the delay.

Analyzing the traffic the problem is that it is not a Storefront.
It is possibly a Citrix Gateway.

We don't have Gateway support yet.
But coincidentally we are right now trying to provide some kind of Gateway support.

In the course of this week we will have a jmx that we could share with you as a test for your evaluation.

Meanwhile, what you can confirm is that if what you want to do is load test over Gateway or over Storefront.

It has happened to us that many times when the infrastructure knows that the load tests will be carried out on the Gateway, it does not want it, and allows access to the Storefront server that is behind it (through a remote machine or vpn).

In the meantime we will be using the information in your har file to try to know more how to interact with Gateway.

Currently we do not have an environment with Gateway to perform the tests, so we will need help from people in the community who have Gateway to be able to test it.

**Comment by AnuragChourasia** [comment]
Thanks David for your response.
I will get confirmation on Citrix Gateway Vs Storefront from my IT team and respond to you.

Regards

**Comment by 3dgiordano** [comment]
Hi @AnuragChourasia 
We made an experimental version for you to test with your Gateway portal.

You can download the jmx from the following link.
https://drive.google.com/file/d/1AhfDl-fQpMfnXqfhAeCh5Hsudnec3BMR/view?usp=sharing

You just have to configure the UDV Server and UDV Credentials section with the valid values for your portal and application that you want to test.

an error occurs, in the ViewResultTree results you should be able to know what the reason is.
In case you can't find the reason for the problem, send us the jtl so we can diagnose what is happening.

If the tests are correct we can add the improvements in a future version of the plugin.

We await the results.

**Comment by 3dgiordano** [comment]
Hi @AnuragChourasia 

A new version of the plugin was released today. 
Citrix Plugin v0.7.5 https://github.com/Blazemeter/CitrixPlugin/releases/tag/0.7.5
The new version brings an initial support of Citrix Gateway

I invite you to try it, in case you have any problem, you can raise a new issue.
The current issue will be closed, as it has had a long time of inactivity with no response.
